[build]
  command = "yarn install && yarn relay && yarn build && yarn build:netlify-functions"
  publish = "build/public"
  functions = "build-netlify-functions/"
  environment = { NETLIFY = "true" }

[context]
  environment = { NETLIFY = "true", AWS_LAMBDA_JS_RUNTIME = "nodejs12.x" }

[template.environment]
  RAZZLE_ONEGRAPH_APP_ID = "Your OneGraph app id"
  RAZZLE_GITHUB_REPO_NAME = "Name of the repo that OneBlog should pull issues from"
  RAZZLE_GITHUB_REPO_OWNER = "Owner of the repo that OneBlog should pull issues from"
  RAZZLE_TITLE = "The title of the blog"
  RAZZLE_DESCRIPTION="Description of the blog"
  RAZZLE_SITE_HOSTNAME="Hostname for your blog, e.g. https://example.com"
  OG_GITHUB_TOKEN = "The server-side token from OneGraph that will be used in persisted queries"
  OG_DASHBOARD_ACCESS_TOKEN = "The OneGraph API token that allows the build to create persisted queries"

[[redirects]]
  from = "/"
  to = "/.netlify/functions/index/"
  status = 200

[[redirects]]
  from = "/post/*"
  to = "/.netlify/functions/index/post/:splat"
  status = 200

[[redirects]]
  from = "/feed*"
  to = "/.netlify/functions/index/feed:splat"
  status = 200

[[redirects]]
  from = "/image-proxy*"
  to = "/.netlify/functions/index/image-proxy:splat"
  status = 200

[[redirects]]
  from = "/first-frame*"
  to = "/.netlify/functions/index/first-frame:splat"
  status = 200
